# Generated by Django 3.1.5 on 2021-10-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20211003_0500'),
        ('recetario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='ingrediente',
        ),
        migrations.AddField(
            model_name='receta',
            name='ingrediente',
            field=models.ManyToManyField(to='stock.Ingrediente'),
        ),
    ]
