# Generated by Django 3.1.5 on 2021-10-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
