# Generated by Django 3.1.5 on 2021-10-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20211003_0356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredientes'},
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='cantidad',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='duracion',
            field=models.DurationField(),
        ),
    ]
