# Generated by Django 3.1.5 on 2021-10-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recetario', '0002_auto_20211003_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entrega', models.DateField()),
                ('descripcion', models.TextField()),
                ('receta', models.ManyToManyField(to='recetario.Receta')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
